version: '3'
services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
#    healthcheck:
#      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-proot", "-e", "show databases"]
#      interval: 10s
#      timeout: 2s
#      retries: 10
#      start_period: 10s
#      #start_interval: "5s"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artus
      MYSQL_USER: user
      MYSQL_PASSWORD: artus
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

#  spring-app-container:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring-app-container
#    depends_on:
#      mysql-container:
#        condition: service_healthy
#    ports:
#      - "8080:8080"

volumes:
  mysql-data: